### ISSUE TITLE
使用透明背景脚本时报“您似乎选择了非iPhone屏幕截图的图像，或者不支持您的iPhone。请使用其他图像再试一次!”

### ISSUE THREAD

**Issue by KylinChan** [samuelshi/Scriptable#1]
如题，使用正确的截图方式生成透明背景时报此错误。
设备：iPhone12

**Comment by samuelshi** [comment]
因为iphone12刚出，还没适配，可以暂时选择普通图像生成。

**Comment by samuelshi** [comment]
> 如题，使用正确的截图方式生成透明背景时报此错误。
> 设备：iPhone12

因为iphone12刚出，还没适配，可以暂时选择普通图像生成。

**Comment by samuelshi** [comment]
已适配，如有问题和我说一下。

**Comment by KylinChan** [comment]
测试后没有问题，谢谢
